# Generated by Django 5.0 on 2023-12-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="products/default.jpg", upload_to="products/images/"
            ),
        ),
    ]
