# Generated by Django 5.0 on 2023-12-16 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_alter_post_options_alter_post_title_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="Body",
        ),
    ]
