# Generated by Django 5.0 on 2023-12-16 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_rename_body_comment_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="Body",
            new_name="body",
        ),
    ]
